import { Bank, Promo, Tip } from './types';

export const BANKS: Bank[] = [
  {
    id: 'kaspi',
    name: 'Kaspi',
    card: 'Kaspi Gold',
    color: '#E53935',
    bg: '#FFEBEE',
    gradient: ['#E53935', '#C62828'],
    type: 'promo',
    desc: 'Кэшбэк только через промо-акции партнёров',
    note: 'Бонусы только в акциях Kaspi',
    url: 'https://kaspi.kz',
    lounge: false,
    insurance: false,
    limits: { monthly: 0 },
    config: {},
    baseRates: {},
  },
  {
    id: 'halyk',
    name: 'Halyk',
    card: 'Halyk Bonus',
    color: '#1B5E20',
    bg: '#E8F5E9',
    gradient: ['#2E7D32', '#1B5E20'],
    type: 'fixed',
    desc: 'Фиксированный кэшбэк, travel до 7%',
    note: 'Лучшая карта для путешествий',
    url: 'https://halykbank.kz',
    lounge: false,
    insurance: false,
    limits: { monthly: 50000 },
    config: {},
    baseRates: {
      grocery: 1,
      restaurants: 1,
      transport: 1,
      clothing: 1,
      entertainment: 1,
      fuel: 1,
      travel: 5,
      pharmacy: 1,
      online: 1,
      telecom: 1,
    },
  },
  {
    id: 'forte',
    name: 'Forte',
    card: 'ForteBlack',
    color: '#212121',
    bg: '#F5F5F5',
    gradient: ['#424242', '#212121'],
    type: 'selectable',
    desc: 'Выбери 3 категории с кэшбэком до 15%',
    note: 'Максимальный кэшбэк при правильном выборе',
    url: 'https://forte.kz',
    lounge: true,
    insurance: true,
    limits: { monthly: 30000, daily: 10000 },
    config: { maxCategories: 3 },
    baseRates: {
      _selected: 15,
      _default: 1,
    },
  },
  {
    id: 'bcc',
    name: 'BCC',
    card: '#картакарта',
    color: '#1565C0',
    bg: '#E3F2FD',
    gradient: ['#1976D2', '#1565C0'],
    type: 'selectable',
    desc: 'Выбери 3 категории с кэшбэком до 10%',
    note: 'Хороший вариант для тех кто хочет выбирать категории',
    url: 'https://bcc.kz',
    lounge: false,
    insurance: false,
    limits: { monthly: 20000 },
    config: { maxCategories: 3 },
    baseRates: {
      _selected: 10,
      _default: 1,
    },
  },
  {
    id: 'freedom',
    name: 'Freedom',
    card: 'Freedom Card',
    color: '#6A1B9A',
    bg: '#F3E5F5',
    gradient: ['#7B1FA2', '#6A1B9A'],
    type: 'leveled',
    desc: 'От 1% до 4% + бонус NFC до +2%',
    note: '4 уровня: чем больше тратишь, тем больше кэшбэк',
    url: 'https://freedomfinance.kz',
    lounge: true,
    insurance: true,
    limits: { monthly: 50000 },
    config: {
      levels: {
        standard: { base: 1, nfc: 0.5 },
        silver: { base: 2, nfc: 1 },
        gold: { base: 3, nfc: 1.5 },
        platinum: { base: 4, nfc: 2 },
      },
    },
    baseRates: {},
  },
  {
    id: 'bereke',
    name: 'Bereke',
    card: 'Bereke Card',
    color: '#00695C',
    bg: '#E0F2F1',
    gradient: ['#00796B', '#00695C'],
    type: 'subscription',
    desc: 'Кэшбэк зависит от суммы депозита: 0–7%',
    note: 'Чем больше депозит, тем выше кэшбэк',
    url: 'https://berekebank.kz',
    lounge: false,
    insurance: false,
    limits: { monthly: 30000 },
    config: {
      tiers: {
        zero: 0,
        basic: 1,
        medium: 3,
        high: 5,
        max: 7,
      },
    },
    baseRates: {},
  },
  {
    id: 'jusan',
    name: 'Alatau City Bank',
    card: 'Alatau Card',
    color: '#F57F17',
    bg: '#FFF8E1',
    gradient: ['#F9A825', '#F57F17'],
    type: 'fixed',
    desc: 'Продукты 3%, аптеки 3%, АЗС 2%, остальное 1%',
    note: 'Хороший кэшбэк на продукты и аптеки',
    url: 'https://alataubank.kz',
    lounge: false,
    insurance: false,
    limits: { monthly: 30000 },
    config: {},
    baseRates: {
      grocery: 3,
      pharmacy: 3,
      fuel: 2,
      restaurants: 1,
      transport: 1,
      clothing: 1,
      entertainment: 1,
      travel: 1,
      online: 1,
      telecom: 1,
    },
  },
];

export const PROMOS: Promo[] = [
  {
    bankId: 'forte',
    title: 'Forte × Starbucks',
    desc: '10% кэшбэк в Starbucks',
    category: 'restaurants',
    rate: 10,
    emoji: '☕',
    endDate: '2026-04-30',
    isNew: true,
  },
  {
    bankId: 'halyk',
    title: 'Halyk × Sinooil',
    desc: '4% кэшбэк на АЗС Sinooil',
    category: 'fuel',
    rate: 4,
    emoji: '⛽',
    endDate: '2026-05-15',
    isNew: false,
  },
  {
    bankId: 'freedom',
    title: 'Freedom × Arbuz',
    desc: '26% кэшбэк в Arbuz',
    category: 'grocery',
    rate: 26,
    emoji: '🍉',
    endDate: '2026-05-31',
    isNew: true,
  },
  {
    bankId: 'bcc',
    title: 'BCC × Kino.kz',
    desc: '5% кэшбэк на Kino.kz',
    category: 'entertainment',
    rate: 5,
    emoji: '🎬',
    endDate: '2026-04-30',
    isNew: false,
  },
];

export const TIPS: Tip[] = [
  {
    id: 'lounge',
    title: 'Бесплатные лаунжи',
    emoji: '✈️',
    items: [
      { text: 'ForteBlack — бесплатный доступ в лаунжи аэропортов', emoji: '🏦' },
      { text: 'Freedom Platinum — лаунжи по Priority Pass', emoji: '💳' },
      { text: 'Проверь условия: количество визитов может быть ограничено', emoji: '⚠️' },
    ],
  },
  {
    id: 'insurance',
    title: 'Страховка путешественников',
    emoji: '🛡',
    items: [
      { text: 'ForteBlack включает страховку при выезде за рубеж', emoji: '🏦' },
      { text: 'Freedom Gold/Platinum — страховка для путешествий', emoji: '💳' },
      { text: 'Покрытие до $50 000 в зависимости от банка', emoji: '💰' },
    ],
  },
  {
    id: 'bonus-vs-cash',
    title: 'Бонусы vs деньги',
    emoji: '💡',
    items: [
      { text: 'Kaspi, Halyk — кэшбэк начисляется бонусами', emoji: '⭐' },
      { text: 'Forte, Freedom — реальные деньги на счёт', emoji: '💵' },
      { text: 'Бонусы могут сгореть, деньги — нет', emoji: '🔥' },
    ],
  },
  {
    id: 'cash-withdrawal',
    title: 'Снятие наличных',
    emoji: '🏧',
    items: [
      { text: 'Kaspi Gold — бесплатно в своих банкоматах', emoji: '✅' },
      { text: 'Freedom — бесплатно до 500 000 ₸/мес', emoji: '✅' },
      { text: 'ForteBlack — без комиссии до 1 000 000 ₸/мес', emoji: '✅' },
    ],
  },
  {
    id: 'nfc',
    title: 'NFC-бонус',
    emoji: '📱',
    items: [
      { text: 'Freedom даёт +0.5–2% при оплате через NFC', emoji: '📶' },
      { text: 'Добавь карту в Apple/Google Pay', emoji: '💳' },
      { text: 'Бонус зависит от уровня: Standard +0.5%, Platinum +2%', emoji: '📊' },
    ],
  },
];
